- name: Install python-apt, aptitude, and debconf-utils
  shell: apt-get update && apt-get -y install python-apt aptitude debconf-utils python-software-properties csh

- name: Set default locale to en_US.UTF-8
  debconf: name=locales question='locales/default_environment_locale' value=en_US.UTF-8 vtype='select'

- name: Generate locales
  debconf: name=locales question='locales/locales_to_be_generated'  value='en_US.UTF-8 UTF-8' vtype='multiselect'

- name: Set timezone area
  debconf: name=tzdata question='tzdata/Areas' value='Etc' vtype='select'

- name: Set timezone
  debconf: name=tzdata question='tzdata/Zones/Etc' value='UTC' vtype='select'
  notify:
  - restart rsyslog
  - restart cron

- name: Install Common Packages
  shell: apt-get -y install python-m2crypto python-paramiko python-pip git wget

- name: Create the hosts file for all machines
  template: src=hosts.j2 dest=/etc/hosts

- name: upload sge env
  template: src=sge.j2 dest=/etc/profile.d/sge.sh

- name: Set SGE Environment Variables
  shell:
    chmod 777 /etc/profile.d/sge.sh; 
    echo "source /etc/profile.d/sge.sh" >> /etc/profile;
    bash -c 'source /etc/profile';
    bash -c 'source /etc/profile.d/sge.sh';
    echo "source /etc/profile.d/sge.sh" >> /home/{{ ansible_ssh_user }}/.bashrc;
    echo 'source /etc/profile.d/sge.sh' >> /home/{{ ansible_ssh_user }}/.profile;
    bash -c 'source /home/{{ ansible_ssh_user }}/.bashrc';


- name: copy private key
  copy: src=id_rsa dest=/home/{{ ansible_ssh_user }}/.ssh/id_rsa

- name: copy public key
  copy: src=id_rsa.pub  dest=/home/{{ ansible_ssh_user }}/.ssh/id_rsa.pub

- name: authorized keys
  shell: cat /home/{{ ansible_ssh_user }}/.ssh/id_rsa.pub > /home/{{ ansible_ssh_user }}/.ssh/authorized_keys

